# Generated by Django 3.1.3 on 2021-04-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
