# Generated by Django 3.1.3 on 2021-05-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_auto_20210429_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('stock_count', models.PositiveIntegerField()),
                ('item_order_count', models.PositiveIntegerField()),
                ('item_price', models.PositiveIntegerField()),
                ('item_description', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.store')),
            ],
        ),
    ]
